# Generated by Django 5.1.1 on 2024-09-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pidor',
        ),
    ]
