# Generated by Django 5.1.1 on 2024-09-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_property_name_remove_property_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
