# Generated by Django 4.2.16 on 2025-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, to='properties.tag'),
        ),
    ]
